module.exports = {
  apps: [
    {
      name: 'api-gateway',
      script: './services/api-gateway/src/main.ts',
      interpreter: 'node',
      interpreter_args: '-r ts-node/register',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT: 3000,
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      error_file: './logs/api-gateway-error.log',
      out_file: './logs/api-gateway-out.log',
      log_file: './logs/api-gateway-combined.log',
      time: true,
    },
    {
      name: 'auth-service',
      script: './services/auth-service/src/main.ts',
      interpreter: 'node',
      interpreter_args: '-r ts-node/register',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'development',
        PORT: 3001,
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 3001,
      },
      error_file: './logs/auth-service-error.log',
      out_file: './logs/auth-service-out.log',
      log_file: './logs/auth-service-combined.log',
      time: true,
    },
    {
      name: 'product-service',
      script: './services/product-service/src/main.ts',
      interpreter: 'node',
      interpreter_args: '-r ts-node/register',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'development',
        PORT: 3002,
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 3002,
      },
      error_file: './logs/product-service-error.log',
      out_file: './logs/product-service-out.log',
      log_file: './logs/product-service-combined.log',
      time: true,
    },
    {
      name: 'order-service',
      script: './services/order-service/src/main.ts',
      interpreter: 'node',
      interpreter_args: '-r ts-node/register',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'development',
        PORT: 3003,
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 3003,
      },
      error_file: './logs/order-service-error.log',
      out_file: './logs/order-service-out.log',
      log_file: './logs/order-service-combined.log',
      time: true,
    },
    {
      name: 'appointment-service',
      script: './services/appointment-service/src/main.ts',
      interpreter: 'node',
      interpreter_args: '-r ts-node/register',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'development',
        PORT: 3004,
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 3004,
      },
      error_file: './logs/appointment-service-error.log',
      out_file: './logs/appointment-service-out.log',
      log_file: './logs/appointment-service-combined.log',
      time: true,
    },
    {
      name: 'customer-service',
      script: './services/customer-service/src/main.ts',
      interpreter: 'node',
      interpreter_args: '-r ts-node/register',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'development',
        PORT: 3005,
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 3005,
      },
      error_file: './logs/customer-service-error.log',
      out_file: './logs/customer-service-out.log',
      log_file: './logs/customer-service-combined.log',
      time: true,
    },
    {
      name: 'content-service',
      script: './services/content-service/src/main.ts',
      interpreter: 'node',
      interpreter_args: '-r ts-node/register',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'development',
        PORT: 3006,
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 3006,
      },
      error_file: './logs/content-service-error.log',
      out_file: './logs/content-service-out.log',
      log_file: './logs/content-service-combined.log',
      time: true,
    },
    {
      name: 'notification-service',
      script: './services/notification-service/src/main.ts',
      interpreter: 'node',
      interpreter_args: '-r ts-node/register',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'development',
        PORT: 3007,
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 3007,
      },
      error_file: './logs/notification-service-error.log',
      out_file: './logs/notification-service-out.log',
      log_file: './logs/notification-service-combined.log',
      time: true,
    },
    {
      name: 'analytics-service',
      script: './services/analytics-service/src/main.ts',
      interpreter: 'node',
      interpreter_args: '-r ts-node/register',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'development',
        PORT: 3008,
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 3008,
      },
      error_file: './logs/analytics-service-error.log',
      out_file: './logs/analytics-service-out.log',
      log_file: './logs/analytics-service-combined.log',
      time: true,
    },
    {
      name: 'upload-service',
      script: './services/upload-service/src/main.ts',
      interpreter: 'node',
      interpreter_args: '-r ts-node/register',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'development',
        PORT: 3009,
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 3009,
      },
      error_file: './logs/upload-service-error.log',
      out_file: './logs/upload-service-out.log',
      log_file: './logs/upload-service-combined.log',
      time: true,
    },
  ],
};
