// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";

export default {
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: "postgres://cd5f5b67fa0e94337c209109319754f47937df0a9bf4d378bd6894bbe9329e70:sk_FlIyNYA_kzbTmmxAf7SQp@db.prisma.io:5432/postgres?sslmode=require",
  },
};
