export const serviceRoutes = {
  auth: {
    base: '/auth',
    routes: [
      { path: '/login', method: 'POST' },
      { path: '/register', method: 'POST' },
      { path: '/logout', method: 'POST' },
      { path: '/refresh', method: 'POST' },
      { path: '/forgot-password', method: 'POST' },
      { path: '/reset-password', method: 'POST' },
      { path: '/change-password', method: 'POST' },
      { path: '/verify-email', method: 'POST' },
      { path: '/resend-verification', method: 'POST' },
      { path: '/users', method: 'GET' },
      { path: '/users', method: 'POST' },
      { path: '/users/:id', method: 'GET' },
      { path: '/users/:id', method: 'PUT' },
      { path: '/users/:id', method: 'DELETE' },
      { path: '/users/me', method: 'GET' },
      { path: '/users/me', method: 'PUT' },
      { path: '/users/me/avatar', method: 'POST' },
      { path: '/roles', method: 'GET' },
      { path: '/roles', method: 'POST' },
      { path: '/roles/:id', method: 'GET' },
      { path: '/roles/:id', method: 'PUT' },
      { path: '/roles/:id', method: 'DELETE' },
      { path: '/sessions', method: 'GET' },
      { path: '/sessions', method: 'DELETE' },
      { path: '/sessions/:id', method: 'DELETE' },
      { path: '/auth/permissions/:permission', method: 'GET' },
      { path: '/auth/permissions', method: 'GET' },
    ],
  },
  products: {
    base: '/products',
    routes: [
      { path: '/categories', method: 'GET' },
      { path: '/categories', method: 'POST' },
      { path: '/categories/:id', method: 'GET' },
      { path: '/categories/:id', method: 'PUT' },
      { path: '/categories/:id', method: 'DELETE' },
      { path: '/categories/:id/toggle-status', method: 'PATCH' },
      { path: '/colours', method: 'GET' },
      { path: '/colours', method: 'POST' },
      { path: '/colours/:id', method: 'GET' },
      { path: '/colours/:id', method: 'PUT' },
      { path: '/colours/:id', method: 'DELETE' },
      { path: '/colours/:id/toggle-status', method: 'PATCH' },
      { path: '/sizes', method: 'GET' },
      { path: '/sizes', method: 'POST' },
      { path: '/sizes/:id', method: 'GET' },
      { path: '/sizes/:id', method: 'PUT' },
      { path: '/sizes/:id', method: 'DELETE' },
      { path: '/sizes/:id/toggle-status', method: 'PATCH' },
      { path: '/', method: 'GET' },
      { path: '/', method: 'POST' },
      { path: '/:id', method: 'GET' },
      { path: '/:id', method: 'PUT' },
      { path: '/:id', method: 'DELETE' },
      { path: '/:id/toggle-status', method: 'PATCH' },
      { path: '/:id/toggle-featured', method: 'PATCH' },
      { path: '/featured', method: 'GET' },
      { path: '/slug/:slug', method: 'GET' },
      { path: '/:id/related', method: 'GET' },
      { path: '/search', method: 'GET' },
      { path: '/inventory', method: 'GET' },
      { path: '/inventory', method: 'POST' },
      { path: '/inventory/:id', method: 'GET' },
      { path: '/inventory/:id', method: 'PUT' },
      { path: '/inventory/:id', method: 'DELETE' },
      { path: '/inventory/:id/quantity', method: 'PATCH' },
      { path: '/inventory/low-stock', method: 'GET' },
      { path: '/pricing', method: 'GET' },
      { path: '/pricing', method: 'POST' },
      { path: '/pricing/:id', method: 'GET' },
      { path: '/pricing/:id', method: 'PUT' },
      { path: '/pricing/:id', method: 'DELETE' },
      { path: '/pricing/:id/start-sale', method: 'PATCH' },
      { path: '/pricing/:id/end-sale', method: 'PATCH' },
      { path: '/pricing/sale', method: 'GET' },
      { path: '/inventory/bulk-update', method: 'POST' },
      { path: '/pricing/bulk-update', method: 'POST' },
    ],
  },
  appointments: {
    base: '/appointments',
    routes: [
      { path: '/', method: 'GET' },
      { path: '/', method: 'POST' },
      { path: '/:id', method: 'GET' },
      { path: '/:id', method: 'PUT' },
      { path: '/:id', method: 'DELETE' },
      { path: '/:id/confirm', method: 'PATCH' },
      { path: '/:id/cancel', method: 'PATCH' },
      { path: '/:id/reschedule', method: 'PATCH' },
      { path: '/customer/:customerId', method: 'GET' },
      { path: '/consultant/:consultantId', method: 'GET' },
      { path: '/availability/check', method: 'POST' },
      { path: '/availability', method: 'GET' },
      { path: '/availability', method: 'POST' },
      { path: '/availability/:id', method: 'PUT' },
      { path: '/availability/:id', method: 'DELETE' },
      { path: '/availability/bulk', method: 'POST' },
      { path: '/time-slots', method: 'GET' },
      { path: '/time-slots', method: 'POST' },
      { path: '/time-slots/:id', method: 'PUT' },
      { path: '/time-slots/:id', method: 'DELETE' },
      { path: '/consultants', method: 'GET' },
      { path: '/consultants', method: 'POST' },
      { path: '/consultants/:id', method: 'GET' },
      { path: '/consultants/:id', method: 'PUT' },
      { path: '/consultants/:id', method: 'DELETE' },
      { path: '/consultants/:id/toggle-status', method: 'PATCH' },
      { path: '/consultants/available', method: 'GET' },
      { path: '/reminders', method: 'GET' },
      { path: '/reminders', method: 'POST' },
      { path: '/reminders/:id', method: 'GET' },
      { path: '/reminders/:id/send', method: 'POST' },
      { path: '/reminders/:id/cancel', method: 'PATCH' },
      { path: '/calendar/:consultantId', method: 'GET' },
      { path: '/calendar/:consultantId/sync', method: 'POST' },
      { path: '/stats', method: 'GET' },
    ],
  },
  customers: {
    base: '/customers',
    routes: [
      { path: '/', method: 'GET' },
      { path: '/', method: 'POST' },
      { path: '/:id', method: 'GET' },
      { path: '/:id', method: 'PUT' },
      { path: '/:id', method: 'DELETE' },
      { path: '/reviews', method: 'GET' },
      { path: '/reviews', method: 'POST' },
      { path: '/reviews/:id', method: 'GET' },
      { path: '/reviews/:id', method: 'PUT' },
      { path: '/support-tickets', method: 'GET' },
      { path: '/support-tickets', method: 'POST' },
      { path: '/support-tickets/:id', method: 'GET' },
      { path: '/support-tickets/:id', method: 'PUT' },
      { path: '/support-tickets/:id/messages', method: 'POST' },
      { path: '/loyalty', method: 'GET' },
      { path: '/loyalty/:id', method: 'GET' },
      { path: '/loyalty/:id/adjust', method: 'POST' },
      { path: '/wishlist', method: 'GET' },
      { path: '/wishlist', method: 'POST' },
      { path: '/wishlist/:id', method: 'DELETE' },
      { path: '/saved-designs', method: 'GET' },
      { path: '/saved-designs', method: 'POST' },
      { path: '/saved-designs/:id', method: 'GET' },
      { path: '/saved-designs/:id', method: 'PUT' },
      { path: '/saved-designs/:id', method: 'DELETE' },
    ],
  },
  content: {
    base: '/content',
    routes: [
      { path: '/blogs', method: 'GET' },
      { path: '/blogs', method: 'POST' },
      { path: '/blogs/:id', method: 'GET' },
      { path: '/blogs/:id', method: 'PUT' },
      { path: '/blogs/:id', method: 'DELETE' },
      { path: '/blog-categories', method: 'GET' },
      { path: '/blog-categories', method: 'POST' },
      { path: '/blog-categories/:id', method: 'GET' },
      { path: '/blog-categories/:id', method: 'PUT' },
      { path: '/blog-categories/:id', method: 'DELETE' },
      { path: '/media-wall', method: 'GET' },
      { path: '/media-wall', method: 'POST' },
      { path: '/media-wall/:id', method: 'GET' },
      { path: '/media-wall/:id', method: 'PUT' },
      { path: '/media-wall/:id', method: 'DELETE' },
      { path: '/cms-pages', method: 'GET' },
      { path: '/cms-pages', method: 'POST' },
      { path: '/cms-pages/:id', method: 'GET' },
      { path: '/cms-pages/:id', method: 'PUT' },
      { path: '/cms-pages/:id', method: 'DELETE' },
      { path: '/showrooms', method: 'GET' },
      { path: '/showrooms', method: 'POST' },
      { path: '/showrooms/:id', method: 'GET' },
      { path: '/showrooms/:id', method: 'PUT' },
      { path: '/showrooms/:id', method: 'DELETE' },
      { path: '/seo', method: 'GET' },
      { path: '/seo/:id', method: 'PUT' },
      { path: '/landing-pages', method: 'GET' },
      { path: '/landing-pages', method: 'POST' },
      { path: '/landing-pages/:id', method: 'GET' },
      { path: '/landing-pages/:id', method: 'PUT' },
      { path: '/landing-pages/:id', method: 'DELETE' },
    ],
  },
  orders: {
    base: '/orders',
    routes: [
      { path: '/', method: 'GET' },
      { path: '/', method: 'POST' },
      { path: '/:id', method: 'GET' },
      { path: '/:id', method: 'PUT' },
      { path: '/:id', method: 'DELETE' },
      { path: '/:id/status', method: 'PATCH' },
      { path: '/payments', method: 'GET' },
      { path: '/payments', method: 'POST' },
      { path: '/payments/:id', method: 'GET' },
      { path: '/payments/webhook', method: 'POST' },
      { path: '/invoices', method: 'GET' },
      { path: '/invoices', method: 'POST' },
      { path: '/invoices/:id', method: 'GET' },
      { path: '/refunds', method: 'GET' },
      { path: '/refunds', method: 'POST' },
      { path: '/refunds/:id', method: 'GET' },
      { path: '/refunds/:id', method: 'PUT' },
    ],
  },
  notifications: {
    base: '/notifications',
    routes: [
      { path: '/', method: 'GET' },
      { path: '/', method: 'POST' },
      { path: '/:id', method: 'GET' },
      { path: '/:id', method: 'PUT' },
      { path: '/:id', method: 'DELETE' },
      { path: '/email', method: 'GET' },
      { path: '/email', method: 'POST' },
      { path: '/email/:id', method: 'GET' },
      { path: '/sms', method: 'GET' },
      { path: '/sms', method: 'POST' },
      { path: '/sms/:id', method: 'GET' },
      { path: '/push', method: 'GET' },
      { path: '/push', method: 'POST' },
      { path: '/push/:id', method: 'GET' },
      { path: '/templates', method: 'GET' },
      { path: '/templates', method: 'POST' },
      { path: '/templates/:id', method: 'GET' },
      { path: '/templates/:id', method: 'PUT' },
      { path: '/templates/:id', method: 'DELETE' },
    ],
  },
  analytics: {
    base: '/analytics',
    routes: [
      { path: '/events', method: 'GET' },
      { path: '/events', method: 'POST' },
      { path: '/events/query', method: 'GET' },
      { path: '/funnels', method: 'GET' },
      { path: '/funnels', method: 'POST' },
      { path: '/funnels/:id', method: 'GET' },
      { path: '/funnels/:id', method: 'PUT' },
      { path: '/funnels/:id', method: 'DELETE' },
      { path: '/dashboards', method: 'GET' },
      { path: '/dashboards', method: 'POST' },
      { path: '/dashboards/:id', method: 'GET' },
      { path: '/dashboards/:id', method: 'PUT' },
      { path: '/dashboards/:id', method: 'DELETE' },
      { path: '/export', method: 'POST' },
    ],
  },
  upload: {
    base: '/upload',
    routes: [
      { path: '/', method: 'POST' },
      { path: '/:id', method: 'GET' },
      { path: '/:id', method: 'DELETE' },
    ],
  },
};
