export const ORDER_CONSTANTS = {
  MAX_ITEMS_PER_ORDER: 50,
  MIN_ORDER_AMOUNT: 1,
  MAX_ORDER_AMOUNT: 999999,
  ORDER_NUMBER_PREFIX: 'LW',
  ORDER_NUMBER_LENGTH: 10,
  DEFAULT_CURRENCY: 'GBP',
  SUPPORTED_CURRENCIES: ['GBP', 'EUR', 'USD'] as const,
  PENDING_EXPIRY_MINUTES: 30,
  AWAITING_PAYMENT_EXPIRY_MINUTES: 60,
  MAX_CANCELLATION_WINDOW_HOURS: 24,
} as const;

export const PAYMENT_CONSTANTS = {
  STRIPE_API_VERSION: '2024-06-20' as const,
  STRIPE_WEBHOOK_TOLERANCE_SECONDS: 300,
  MAX_RETRY_ATTEMPTS: 3,
  RETRY_BACKOFF_BASE_MS: 1000,
  RETRY_BACKOFF_MAX_MS: 30000,
  PAYMENT_INTENT_CAPTURE_METHOD: 'automatic' as const,
  SUPPORTED_PAYMENT_METHODS: ['card'] as const,
  STATEMENT_DESCRIPTOR: 'LOMASH WOOD',
  STATEMENT_DESCRIPTOR_SUFFIX: 'ORDER',
  MIN_CHARGE_AMOUNT_GBP: 30,
} as const;

export const REFUND_CONSTANTS = {
  MAX_REFUND_WINDOW_DAYS: 30,
  MIN_REFUND_AMOUNT: 1,
  STRIPE_REFUND_REASON_MAP: {
    CUSTOMER_REQUEST: 'requested_by_customer',
    FRAUDULENT_CHARGE: 'fraudulent',
    DUPLICATE_CHARGE: 'duplicate',
  } as const,
  PARTIAL_REFUND_MIN_REMAINING: 1,
} as const;

export const INVOICE_CONSTANTS = {
  INVOICE_NUMBER_PREFIX: 'INV',
  INVOICE_NUMBER_LENGTH: 8,
  INVOICE_DUE_DAYS: 30,
  VAT_RATE_STANDARD: 0.2,
  VAT_RATE_ZERO: 0,
  COMPANY_NAME: 'Lomash Wood Ltd',
  COMPANY_ADDRESS_LINE1: '',
  COMPANY_ADDRESS_LINE2: '',
  COMPANY_VAT_NUMBER: '',
  COMPANY_REGISTRATION_NUMBER: '',
} as const;

export const ABANDONED_CHECKOUT_CONSTANTS = {
  ABANDON_THRESHOLD_MINUTES: 30,
  BATCH_SIZE: 100,
  JOB_CRON_EXPRESSION: '*/15 * * * *',
} as const;

export const EXPIRE_ORDER_CONSTANTS = {
  PENDING_EXPIRY_MINUTES: 30,
  AWAITING_PAYMENT_EXPIRY_MINUTES: 60,
  BATCH_SIZE: 100,
  JOB_CRON_EXPRESSION: '*/10 * * * *',
} as const;

export const RECONCILE_PAYMENT_CONSTANTS = {
  LOOKBACK_HOURS: 24,
  BATCH_SIZE: 50,
  JOB_CRON_EXPRESSION: '0 * * * *',
  DISCREPANCY_THRESHOLD_PENCE: 1,
} as const;

export const WEBHOOK_CONSTANTS = {
  MAX_RETRY_ATTEMPTS: 5,
  INITIAL_RETRY_DELAY_MS: 5000,
  MAX_RETRY_DELAY_MS: 300000,
  RETRY_MULTIPLIER: 2,
  JOB_CRON_EXPRESSION: '*/5 * * * *',
  BATCH_SIZE: 20,
  SUPPORTED_STRIPE_EVENTS: [
    'payment_intent.succeeded',
    'payment_intent.payment_failed',
    'payment_intent.canceled',
    'charge.refunded',
    'charge.dispute.created',
    'charge.dispute.closed',
    'customer.subscription.deleted',
  ] as const,
} as const;

export const PAGINATION_CONSTANTS = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 100,
  MIN_LIMIT: 1,
} as const;

export const CACHE_TTL = {
  ORDER_SECONDS: 60,
  PAYMENT_SECONDS: 30,
  INVOICE_SECONDS: 300,
  PRODUCT_PRICE_SECONDS: 120,
} as const;

export const CACHE_KEY_PREFIX = {
  ORDER: 'order:',
  PAYMENT: 'payment:',
  INVOICE: 'invoice:',
  REFUND: 'refund:',
  CHECKOUT_SESSION: 'checkout:session:',
  IDEMPOTENCY: 'idempotency:',
} as const;

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  PAYMENT_REQUIRED: 402,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
} as const;

export const SORT_ORDER = {
  ASC: 'asc',
  DESC: 'desc',
} as const;

export const ENVIRONMENT = {
  DEVELOPMENT: 'development',
  STAGING: 'staging',
  PRODUCTION: 'production',
  TEST: 'test',
} as const;