export const AUTH_CONSTANTS = {
  JWT: {
    ACCESS_TOKEN_EXPIRY: '15m',
    REFRESH_TOKEN_EXPIRY: '7d',
    PASSWORD_RESET_TOKEN_EXPIRY: '1h',
    EMAIL_VERIFICATION_TOKEN_EXPIRY: '24h',
    OTP_EXPIRY: '5m',
  },
  PASSWORD: {
    MIN_LENGTH: 8,
    MAX_LENGTH: 128,
    REQUIRE_UPPERCASE: true,
    REQUIRE_LOWERCASE: true,
    REQUIRE_NUMBER: true,
    REQUIRE_SPECIAL_CHAR: true,
    SALT_ROUNDS: 12,
  },
  SESSION: {
    MAX_ACTIVE_SESSIONS: 5,
    IDLE_TIMEOUT: 30 * 60 * 1000,
    ABSOLUTE_TIMEOUT: 24 * 60 * 60 * 1000,
    COOKIE_NAME: 'lomash_session',
    COOKIE_MAX_AGE: 7 * 24 * 60 * 60 * 1000,
  },
  RATE_LIMIT: {
    LOGIN_MAX_ATTEMPTS: 5,
    LOGIN_WINDOW_MS: 15 * 60 * 1000,
    PASSWORD_RESET_MAX_ATTEMPTS: 3,
    PASSWORD_RESET_WINDOW_MS: 60 * 60 * 1000,
    REGISTRATION_MAX_ATTEMPTS: 3,
    REGISTRATION_WINDOW_MS: 60 * 60 * 1000,
    OTP_MAX_ATTEMPTS: 5,
    OTP_WINDOW_MS: 15 * 60 * 1000,
  },
  LOCKOUT: {
    MAX_FAILED_ATTEMPTS: 5,
    LOCKOUT_DURATION_MS: 30 * 60 * 1000,
    RESET_ATTEMPTS_AFTER_MS: 60 * 60 * 1000,
  },
  OTP: {
    LENGTH: 6,
    NUMERIC_ONLY: true,
    EXPIRY_MINUTES: 5,
    MAX_RESEND_ATTEMPTS: 3,
    RESEND_COOLDOWN_MS: 60 * 1000,
  },
  ROLES: {
    SUPER_ADMIN: 'SUPER_ADMIN',
    ADMIN: 'ADMIN',
    MANAGER: 'MANAGER',
    STAFF: 'STAFF',
    CUSTOMER: 'CUSTOMER',
    GUEST: 'GUEST',
  },
  PERMISSIONS: {
    USER_READ: 'user:read',
    USER_WRITE: 'user:write',
    USER_DELETE: 'user:delete',
    ROLE_READ: 'role:read',
    ROLE_WRITE: 'role:write',
    ROLE_DELETE: 'role:delete',
    SESSION_READ: 'session:read',
    SESSION_WRITE: 'session:write',
    SESSION_DELETE: 'session:delete',
  },
  VALIDATION: {
    EMAIL_REGEX: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
    PHONE_REGEX: /^[\d\s\+\-\(\)]+$/,
    POSTCODE_REGEX: /^[A-Z]{1,2}\d{1,2}[A-Z]?\s?\d[A-Z]{2}$/i,
    NAME_MIN_LENGTH: 2,
    NAME_MAX_LENGTH: 100,
  },
  COOKIE: {
    HTTP_ONLY: true,
    SECURE: true,
    SAME_SITE: 'strict' as const,
    PATH: '/',
    DOMAIN: process.env['COOKIE_DOMAIN'] || undefined,
  },
  CACHE: {
    USER_TTL: 60 * 60,
    SESSION_TTL: 60 * 60,
    ROLE_TTL: 24 * 60 * 60,
    PERMISSION_TTL: 24 * 60 * 60,
    TOKEN_BLACKLIST_TTL: 7 * 24 * 60 * 60,
  },
  PAGINATION: {
    DEFAULT_PAGE: 1,
    DEFAULT_LIMIT: 10,
    MAX_LIMIT: 100,
  },
  TOKEN_TYPES: {
    ACCESS: 'ACCESS',
    REFRESH: 'REFRESH',
    PASSWORD_RESET: 'PASSWORD_RESET',
    EMAIL_VERIFICATION: 'EMAIL_VERIFICATION',
  },
  USER_STATUS: {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
    SUSPENDED: 'SUSPENDED',
    DELETED: 'DELETED',
    PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  },
  LOGIN_METHODS: {
    EMAIL: 'email',
    OAUTH: 'oauth',
    SSO: 'sso',
  },
  OAUTH_PROVIDERS: {
    GOOGLE: 'google',
    FACEBOOK: 'facebook',
    APPLE: 'apple',
  },
  HEADERS: {
    AUTHORIZATION: 'Authorization',
    REFRESH_TOKEN: 'X-Refresh-Token',
    API_KEY: 'X-API-Key',
    DEVICE_ID: 'X-Device-ID',
    USER_AGENT: 'User-Agent',
    IP_ADDRESS: 'X-Forwarded-For',
  },
  EVENTS: {
    USER_CREATED: 'USER_CREATED',
    USER_UPDATED: 'USER_UPDATED',
    USER_DELETED: 'USER_DELETED',
    USER_LOGGED_IN: 'USER_LOGGED_IN',
    USER_LOGGED_OUT: 'USER_LOGGED_OUT',
    PASSWORD_CHANGED: 'PASSWORD_CHANGED',
    PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
    PASSWORD_RESET_COMPLETED: 'PASSWORD_RESET_COMPLETED',
    EMAIL_VERIFIED: 'EMAIL_VERIFIED',
    ROLE_ASSIGNED: 'ROLE_ASSIGNED',
    ROLE_REVOKED: 'ROLE_REVOKED',
    SESSION_CREATED: 'SESSION_CREATED',
    SESSION_EXPIRED: 'SESSION_EXPIRED',
    ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
    ACCOUNT_UNLOCKED: 'ACCOUNT_UNLOCKED',
  },
  ERROR_MESSAGES: {
    INVALID_CREDENTIALS: 'Invalid email or password',
    USER_NOT_FOUND: 'User not found',
    USER_ALREADY_EXISTS: 'User with this email already exists',
    EMAIL_NOT_VERIFIED: 'Please verify your email before logging in',
    ACCOUNT_LOCKED: 'Your account has been locked due to multiple failed login attempts',
    ACCOUNT_DISABLED: 'Your account has been disabled',
    SESSION_EXPIRED: 'Your session has expired. Please login again',
    INVALID_TOKEN: 'Invalid or expired token',
    WEAK_PASSWORD: 'Password does not meet security requirements',
    PASSWORD_MISMATCH: 'Passwords do not match',
    INVALID_OTP: 'Invalid or expired OTP',
    MAX_SESSIONS_EXCEEDED: 'Maximum number of active sessions exceeded',
    UNAUTHORIZED: 'You are not authorized to perform this action',
    INVALID_EMAIL: 'Invalid email format',
    INVALID_PHONE: 'Invalid phone number format',
    REQUIRED_FIELD: 'This field is required',
  },
  SUCCESS_MESSAGES: {
    LOGIN_SUCCESS: 'Login successful',
    LOGOUT_SUCCESS: 'Logout successful',
    REGISTRATION_SUCCESS: 'Registration successful',
    PASSWORD_RESET_EMAIL_SENT: 'Password reset email sent successfully',
    PASSWORD_RESET_SUCCESS: 'Password reset successful',
    PASSWORD_CHANGED: 'Password changed successfully',
    EMAIL_VERIFIED: 'Email verified successfully',
    PROFILE_UPDATED: 'Profile updated successfully',
    OTP_SENT: 'OTP sent successfully',
  },
  AUDIT: {
    ACTIONS: {
      LOGIN: 'LOGIN',
      LOGOUT: 'LOGOUT',
      REGISTER: 'REGISTER',
      PASSWORD_RESET: 'PASSWORD_RESET',
      PASSWORD_CHANGE: 'PASSWORD_CHANGE',
      EMAIL_VERIFY: 'EMAIL_VERIFY',
      PROFILE_UPDATE: 'PROFILE_UPDATE',
      ROLE_CHANGE: 'ROLE_CHANGE',
      PERMISSION_GRANT: 'PERMISSION_GRANT',
      PERMISSION_REVOKE: 'PERMISSION_REVOKE',
    },
    RETENTION_DAYS: 90,
  },
} as const;

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
} as const;

export const REGEX_PATTERNS = {
  EMAIL: /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/,
  PASSWORD_STRONG: /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/,
  PHONE_UK: /^(\+44\s?7\d{3}|\(?07\d{3}\)?)\s?\d{3}\s?\d{3}$/,
  POSTCODE_UK: /^[A-Z]{1,2}\d{1,2}[A-Z]?\s?\d[A-Z]{2}$/i,
  UUID: /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,
  ALPHANUMERIC: /^[a-zA-Z0-9]+$/,
  ALPHA_ONLY: /^[a-zA-Z]+$/,
  NUMERIC_ONLY: /^[0-9]+$/,
} as const;

export const DATE_FORMATS = {
  ISO_8601: 'YYYY-MM-DDTHH:mm:ss.SSSZ',
  DATE_ONLY: 'YYYY-MM-DD',
  TIME_ONLY: 'HH:mm:ss',
  DISPLAY: 'DD/MM/YYYY',
  DISPLAY_WITH_TIME: 'DD/MM/YYYY HH:mm',
} as const;

export const ENVIRONMENT = {
  DEVELOPMENT: 'development',
  STAGING: 'staging',
  PRODUCTION: 'production',
  TEST: 'test',
} as const;

export type Role = typeof AUTH_CONSTANTS.ROLES[keyof typeof AUTH_CONSTANTS.ROLES];
export type Permission = typeof AUTH_CONSTANTS.PERMISSIONS[keyof typeof AUTH_CONSTANTS.PERMISSIONS];
export type UserStatus = typeof AUTH_CONSTANTS.USER_STATUS[keyof typeof AUTH_CONSTANTS.USER_STATUS];
export type TokenType = typeof AUTH_CONSTANTS.TOKEN_TYPES[keyof typeof AUTH_CONSTANTS.TOKEN_TYPES];
export type LoginMethod = typeof AUTH_CONSTANTS.LOGIN_METHODS[keyof typeof AUTH_CONSTANTS.LOGIN_METHODS];
export type OAuthProvider = typeof AUTH_CONSTANTS.OAUTH_PROVIDERS[keyof typeof AUTH_CONSTANTS.OAUTH_PROVIDERS];
export type AuditAction = typeof AUTH_CONSTANTS.AUDIT.ACTIONS[keyof typeof AUTH_CONSTANTS.AUDIT.ACTIONS];